### PR TITLE
Fix ISRU config

### LINKED ISSUE #7: Make new ISRU so vanilla ISRU isn't touched
This would allow for balancing our own parts without messing with stock.

### PR DESCRIPTION
**Pull request by BenjaminCronin**
This should be correct, I dont have much experience with MM but that should do it.
Should fix #7 and #10.

### CODE REVIEW

**Comment by Lilithvia** [comment]
Thank you good sir!

**Comment by BenjaminCronin** [comment]
Happy to help! Just to make sure, does the patch work? I wouldn't want to supply you with a broken config...

**Comment by Lilithvia** [comment]
I will check that myself, if you want, go ahead and assign yourself a permanent commit branch while I do that

**Comment by Lilithvia** [comment]
This also appears to fix #8 while my KSP is loading

**Comment by Lilithvia** [comment]
Also, we do have a discord, if you are interested in that kind of thing

**Comment by BenjaminCronin** [comment]
Sure, you have a link?

**Comment by Lilithvia** [comment]
https://discord.gg/pFuxVxT

**Pull request merged**
